version: "3.8"

# 申明同一个网络
networks:
  daigou_admin_net:
    name: daigou_admin_net
    # external: true # 申明网络已经在外部创建

# 游戏数据卷
volumes:
  daigou_admin_nginxdata:
    name: daigou_admin_nginxdata
  daigou_admin_redisdata:
    name: daigou_admin_redisdata
  daigou_admin_mysqldata:
    name: daigou_admin_mysqldata

# 服务
services:
  daigou_admin_redis:
    image: redis:6.0.2-alpine
    restart: always
    # ports:
    #   - "7001:6379"
    networks:
      daigou_admin_net:
        # 给网络取别名,可以用redis和cache找到
        aliases:
          - cache
    command: /usr/local/etc/redis/redis.conf
    volumes:
      # 持久存储redis的数据
      - daigou_admin_redisdata:/data
      # 挂载本地配置文件
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/usr/local/etc/localtime

  daigou_admin_mysql:
    image: mysql:8.0.20
    restart: always
    # ports:
    #   - 7002:3306
    environment:
      MYSQL_ROOT_PASSWORD: daigou_admin123
      MYSQL_DATABASE: daigou_admin
      MYSQL_USER: daigou_admin
      MYSQL_PASSWORD: daigou_admin
    networks:
      daigou_admin_net:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d:rw
      - daigou_admin_mysqldata:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql:rw
      - /etc/localtime:/usr/local/etc/localtime

  daigou_admin_nginx:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ../web:/usr/share/nginx/web
      - ./nginx/cert/:/usr/local/nginx/cert
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx/:rw
      - daigou_admin_nginxdata/:/var/cache/nginx
      - /etc/localtime:/usr/local/etc/localtime
      - daigou_admin_nginxdata/:/run
    networks:
      - daigou_admin_net
    ports:
      - 7000-7010:7000-7010
      - 80:80
      - 443:443
    depends_on:
      - daigou_admin_redis
      - daigou_admin_mysql
      - daigou_admin_server

  daigou_admin_web:
    image: node:14.5.0-alpine
    networks:
      daigou_admin_net:
    # ports:
    #   - 8082:8082
    volumes:
      - ./web:/usr/local/work
      - ./web/node/node_global:/usr/local/node_global
      - ./web/node/node_cache:/usr/local/node_cache
      - ../web:/usr/local/work/code
      - /etc/localtime:/etc/localtime
    working_dir: /usr/local/work
    # entrypoint: ["./start.sh"]
    # 模拟一个伪终端
    tty: true
    depends_on:
      - daigou_admin_redis
      - daigou_admin_mysql
      - daigou_admin_server

  daigou_admin_server:
    image: golang:alpine
    networks:
      daigou_admin_net:
    # ports:
    #   - 8888:8888
    volumes:
      - ./server:/usr/local/work:rw
      - ./server/goenv:/go
      - ../server:/usr/local/work/code:rw
      - /etc/localtime:/etc/localtime
    working_dir: /usr/local/work
    entrypoint: ["./start.sh"]
    # 模拟一个伪终端
    tty: true
    depends_on:
      - daigou_admin_mysql
      - daigou_admin_redis   